import React, { useState, useEffect } from 'react';
import { PortfolioSelect, usePortfolios } from '../../context/PortfolioContext.jsx';
import { api } from '../../api/client.js';
import { SampleDataNotice, PageHeader, Card, Badge, fmtNumber } from '../../components/ui.jsx';

export default function DailyObligationReport() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  // The date filter is bound to this below; without the state it was a bare
  // undeclared identifier and the page threw on first render.
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [layout, setLayout] = useState('SPLIT'); // 'SPLIT' (1-48 | 49-96) or 'SINGLE'
  const { activeId: portfolio } = usePortfolios();
  const [sapModalOpen, setSapModalOpen] = useState(false);
  const [pdfModalOpen, setPdfModalOpen] = useState(false);

  const fetchDOR = async () => {
    setLoading(true);
    try {
      setData(await api.tradingOps.dor({ date, portfolio }));
    } catch (err) {
      console.error('Failed to fetch DOR', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDOR();
  }, [date, portfolio]);

  const renderVolume = (mw) => {
    if (mw === 0) return <span style={{ color: '#6c757d' }}>0.00</span>;
    if (mw < 0) return <span style={{ color: '#27ae60', fontWeight: 'bold' }}>{mw.toFixed(2)}</span>; // Green for cleared injection
    return <span>{mw.toFixed(2)}</span>;
  };

  const renderMcp = (mcp, volume) => {
    if (mcp >= 8000) {
      return <Badge type="success" style={{ background: '#f1c40f', color: '#000', fontWeight: 'bold' }}>₹ {fmtNumber(mcp)}</Badge>; // Gold
    }
    // For zero-cleared blocks, show MCP normally but slightly faded
    if (volume === 0) {
       return <span style={{ color: '#6c757d' }}>{fmtNumber(mcp)}</span>;
    }
    return <span>{fmtNumber(mcp)}</span>;
  };

  const getRowStyle = (block) => {
    if (block.volume_mw < 0) return { background: '#e8f5e9', borderBottom: '1px solid #c8e6c9' }; // Cleared & Generating
    if (block.volume_mw === 0) return { background: '#f8f9fa', borderBottom: '1px solid #dee2e6' }; // Zero Cleared (Recorded Price)
    return { borderBottom: '1px solid #eee' };
  };

  const TableHeader = () => (
    <thead>
      <tr style={{ background: '#343a40', color: '#fff' }}>
        <th scope="col" style={{ padding: 8, textAlign: 'left' }}>Time Block</th>
        <th scope="col" style={{ padding: 8, textAlign: 'right' }}>Qty (MW)</th>
        <th scope="col" style={{ padding: 8, textAlign: 'right' }}>Rate (₹/MWh)</th>
        <th scope="col" style={{ padding: 8, textAlign: 'right' }}>Amount (₹)</th>
      </tr>
    </thead>
  );

  const TableRow = ({ block }) => (
    <tr key={block.block_no} style={getRowStyle(block)}>
      <td style={{ padding: 8 }}>{block.time_label}</td>
      <td style={{ padding: 8, textAlign: 'right' }}>{renderVolume(block.volume_mw)}</td>
      <td style={{ padding: 8, textAlign: 'right' }}>{renderMcp(block.mcp, block.volume_mw)}</td>
      <td style={{ padding: 8, textAlign: 'right' }}>
         {block.trade_value === 0 ? <span style={{ color: '#6c757d' }}>0.00</span> : fmtNumber(block.trade_value)}
      </td>
    </tr>
  );

  return (
    <div style={{ padding: 20, maxWidth: 1600, margin: '0 auto' }}>
      <SampleDataNotice detail="Block volumes, MCP, charges and the net payout on this report are generated by the API stub, not settled trade data. Do not use these figures for settlement or SAP posting." />

      <PageHeader 
        title="Daily Obligation Report (DOR) & Settlement" 
        actions={
          <div style={{ display: 'flex', gap: 10 }}>
            <button className="btn btn-primary" style={{ background: '#34495e' }} onClick={() => setPdfModalOpen(true)}>
              [ View Official IEX PDF ]
            </button>
            <button className="btn btn-primary" style={{ background: '#d35400' }}>[ PDF v ] Export</button>
            <button className="btn btn-primary" style={{ background: '#28a745' }}>[ EXCEL v ] Export</button>
            {data && data.financial_summary && (
               <button className="btn btn-primary" style={{ background: '#8e44ad' }} onClick={() => setSapModalOpen(true)}>
                 Generate SAP FI Journal Entry
               </button>
            )}
          </div>
        }
      />

      <Card style={{ marginBottom: 20, background: '#f5f7f9' }}>
        <div style={{ display: 'flex', gap: 20, alignItems: 'center' }}>
          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 'bold', marginBottom: 5 }} htmlFor="dailyobligationreport-trading-date">Trading Date:</label>
            <input id="dailyobligationreport-trading-date" type="date" className="input" value={date} onChange={e => setDate(e.target.value)} />
          </div>
          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 'bold', marginBottom: 5 }} htmlFor="dailyobligationreport-portfolio-tag">Portfolio Tag:</label>
            <PortfolioSelect id="dailyobligationreport-portfolio-tag" scope="global" allLabel="-- Select portfolio --" />
          </div>
          <div style={{ marginLeft: 'auto', borderLeft: '1px solid #ccc', paddingLeft: 20 }}>
            <span style={{ display: 'block', fontSize: 12, fontWeight: 'bold', marginBottom: 5 }}>Matrix Layout:</span>
            <div role="group" aria-label="Matrix Layout" style={{ display: 'flex', gap: 5 }}>
              <button 
                className={`btn btn-sm ${layout === 'SPLIT' ? 'btn-primary' : 'btn-outline'}`}
                onClick={() => setLayout('SPLIT')}
              >
                Split Grid (1-48 | 49-96)
              </button>
              <button 
                className={`btn btn-sm ${layout === 'SINGLE' ? 'btn-primary' : 'btn-outline'}`}
                onClick={() => setLayout('SINGLE')}
              >
                Single Column (1-96)
              </button>
            </div>
          </div>
        </div>
      </Card>

      <Card>
        {loading || !data ? (
          <div style={{ padding: 40, textAlign: 'center', color: '#666' }}>Loading DOR Data...</div>
        ) : (
          <div>
            <div style={{ marginBottom: 20, padding: 15, background: '#e9ecef', borderRadius: 4, display: 'flex', justifyContent: 'space-between' }}>
              <div>
                <strong>Client:</strong> {data.portfolio}
              </div>
              <div>
                <strong>Date:</strong> {data.date}
              </div>
            </div>

            {/* The clearance status printed here used to be a fixed string
                claiming an active NOC valid to 31-DEC-2026, regardless of the
                portfolio or the real record. A settlement report asserting an
                open-access approval that was never checked is the kind of claim
                an auditor would rely on, so it states the gap instead. */}
            <div style={{ marginBottom: 20, padding: '10px 15px', background: 'var(--slate-50)', color: 'var(--slate-600)', borderRadius: 4, border: '1px solid var(--slate-200)' }}>
               <strong>Standing Clearance (NOC):</strong> not shown — this report is not yet linked to the
               portfolio's clearance record. Check the client's clearance on the bidding screen.
            </div>

            <div style={{ display: 'flex', gap: 15, marginBottom: 10, fontSize: 12 }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: 5 }}><div style={{width: 12, height: 12, background: '#e8f5e9', border: '1px solid #c8e6c9'}}></div> Cleared & Generating</span>
                <span style={{ display: 'flex', alignItems: 'center', gap: 5 }}><div style={{width: 12, height: 12, background: '#f8f9fa', border: '1px solid #dee2e6'}}></div> Zero Cleared (Price Recorded)</span>
            </div>

            {layout === 'SPLIT' ? (
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 40 }}>
                {/* Left Column 1-48 */}
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                  <TableHeader />
                  <tbody>
                    {data.blocks.slice(0, 48).map(b => <TableRow key={b.block_no} block={b} />)}
                  </tbody>
                </table>
                {/* Right Column 49-96 */}
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                  <TableHeader />
                  <tbody>
                    {data.blocks.slice(48, 96).map(b => <TableRow key={b.block_no} block={b} />)}
                  </tbody>
                </table>
              </div>
            ) : (
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                <TableHeader />
                <tbody>
                  {data.blocks.map(b => <TableRow key={b.block_no} block={b} />)}
                </tbody>
              </table>
            )}

            <div style={{ marginTop: 30, borderTop: '2px solid #000', paddingTop: 20 }}>
              <table style={{ width: '100%', fontSize: 16, fontWeight: 'bold' }}>
                <tbody>
                  <tr>
                    <td style={{ width: '50%' }}>TOTAL SUMMARY (96 BLOCKS)</td>
                    <td style={{ textAlign: 'right', paddingRight: 20 }}>Energy Cleared: <span style={{ color: '#2980b9' }}>{fmtNumber(data.summary.total_mwh)} MWh</span></td>
                    <td style={{ textAlign: 'right', paddingRight: 20 }}>Avg Rate: <span style={{ color: '#27ae60' }}>₹{fmtNumber(data.summary.weighted_avg_rate)}/MWh</span></td>
                    <td style={{ textAlign: 'right', color: '#c0392b' }}>Revenue: ₹{fmtNumber(data.summary.total_revenue)}</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div style={{ marginTop: 60, display: 'flex', justifyContent: 'flex-end', paddingRight: 40 }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ borderBottom: '1px solid #000', width: 200, marginBottom: 5 }}></div>
                <strong>{data.signatory.name}</strong><br />
                <span style={{ fontSize: 12, color: '#666' }}>{data.signatory.designation}</span>
              </div>
            </div>

            {/* FINANCIAL SETTLEMENT WATERFALL */}
            {data.financial_summary && (
              <div style={{ marginTop: 40 }}>
                <h3 style={{ borderBottom: '2px solid #ccc', paddingBottom: 10 }}>FINANCIAL SETTLEMENT SUMMARY (IEX REPORT - I)</h3>
                <div style={{ background: '#f8f9fa', padding: 20, borderRadius: 8, border: '1px solid #dee2e6', width: '50%' }}>
                   <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10, fontSize: 16 }}>
                      <span>Gross Traded Value:</span>
                      <strong>₹ {fmtNumber(data.financial_summary.gross_revenue)}</strong>
                   </div>
                   <div style={{ borderBottom: '1px dotted #ccc', margin: '10px 0' }}></div>
                   
                   <div style={{ display: 'flex', justifyContent: 'space-between', color: '#c0392b', marginBottom: 5 }}>
                      <span>(-) NLDC Application Fees:</span>
                      <span>- ₹ {fmtNumber(data.financial_summary.nldc_fee)}</span>
                   </div>
                   <div style={{ display: 'flex', justifyContent: 'space-between', color: '#c0392b', marginBottom: 5 }}>
                      <span>(-) CTU Transmission Charges:</span>
                      <span>- ₹ {fmtNumber(data.financial_summary.ctu_charges)}</span>
                   </div>
                   <div style={{ display: 'flex', justifyContent: 'space-between', color: '#c0392b', marginBottom: 5 }}>
                      <span>(-) STU Transmission Charges (HPPTCL):</span>
                      <span>- ₹ {fmtNumber(data.financial_summary.stu_charges)}</span>
                   </div>
                   <div style={{ display: 'flex', justifyContent: 'space-between', color: '#c0392b', marginBottom: 5 }}>
                      <span>(-) SLDC Scheduling Charges:</span>
                      <span>- ₹ {fmtNumber(data.financial_summary.sldc_charges)}</span>
                   </div>
                   <div style={{ display: 'flex', justifyContent: 'space-between', color: '#c0392b', marginBottom: 5 }}>
                      <span>(-) IEX Transaction Fees:</span>
                      <span>- ₹ {fmtNumber(data.financial_summary.iex_fees)}</span>
                   </div>
                   <div style={{ display: 'flex', justifyContent: 'space-between', color: '#c0392b', marginBottom: 5 }}>
                      <span>(-) Applicable Taxes (IGST 18%):</span>
                      <span>- ₹ {fmtNumber(data.financial_summary.igst)}</span>
                   </div>

                   <div style={{ borderBottom: '2px solid #000', margin: '15px 0' }}></div>
                   <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 18, color: '#27ae60' }}>
                      <strong>NET RECEIVABLE:</strong>
                      <strong>₹ {fmtNumber(data.financial_summary.net_payout)}</strong>
                   </div>
                   <div style={{ textAlign: 'right', marginTop: 10 }}>
                      <Badge type="success">MATCHED WITH IEX PORTAL</Badge>
                   </div>
                </div>
              </div>
            )}
          </div>
        )}
      </Card>

      {/* SAP Export Modal */}
      {sapModalOpen && data?.financial_summary && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
           <div style={{ background: '#fff', width: 800, borderRadius: 8, padding: 30, boxShadow: '0 4px 20px rgba(0,0,0,0.2)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #eee', paddingBottom: 15, marginBottom: 20 }}>
                 <h3 style={{ margin: 0 }}>SAP FI Journal Voucher Preview <span style={{ fontSize: 12, fontWeight: 400, color: 'var(--amber-strong)' }}>· sample figures</span></h3>
                 <button onClick={() => setSapModalOpen(false)} style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer' }}>&times;</button>
              </div>
              
              <div style={{ marginBottom: 20, fontSize: 14 }}>
                 <strong>Document Date:</strong> {data.date} &nbsp;|&nbsp; 
                 <strong>Posting Date:</strong> {new Date().toISOString().split('T')[0]} &nbsp;|&nbsp;
                 <strong>Company Code:</strong> SJVN &nbsp;|&nbsp;
                 <strong>Currency:</strong> INR
              </div>

              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13, marginBottom: 20 }}>
                 <thead>
                    <tr style={{ background: '#f5f7f9' }}>
                       <th scope="col" style={{ padding: 10, borderBottom: '2px solid #ccc', textAlign: 'left' }}>GL Account Name</th>
                       <th scope="col" style={{ padding: 10, borderBottom: '2px solid #ccc', textAlign: 'center' }}>Cost Center</th>
                       <th scope="col" style={{ padding: 10, borderBottom: '2px solid #ccc', textAlign: 'right' }}>Debit (₹)</th>
                       <th scope="col" style={{ padding: 10, borderBottom: '2px solid #ccc', textAlign: 'right' }}>Credit (₹)</th>
                    </tr>
                 </thead>
                 <tbody>
                    <tr>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee' }}>Exchange Settlement Clearing Account</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'center' }}>-</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>{fmtNumber(data.financial_summary.net_payout)}</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>0.00</td>
                    </tr>
                    <tr>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee' }}>STU / SLDC Expense Account</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'center' }}>NAITWAR_HEP</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>{fmtNumber(data.financial_summary.stu_charges + data.financial_summary.sldc_charges + data.financial_summary.nldc_fee)}</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>0.00</td>
                    </tr>
                    <tr>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee' }}>Exchange Fee Expense Account</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'center' }}>NAITWAR_HEP</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>{fmtNumber(data.financial_summary.iex_fees)}</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>0.00</td>
                    </tr>
                    <tr>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee' }}>Input Tax Credit (IGST)</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'center' }}>-</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>{fmtNumber(data.financial_summary.igst)}</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>0.00</td>
                    </tr>
                    <tr>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee' }}>Power Sale Revenue Account</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'center' }}>NAITWAR_HEP</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>0.00</td>
                       <td style={{ padding: 10, borderBottom: '1px solid #eee', textAlign: 'right' }}>{fmtNumber(data.financial_summary.gross_revenue)}</td>
                    </tr>
                 </tbody>
                 <tfoot>
                    <tr style={{ fontWeight: 'bold', background: '#e9ecef' }}>
                       <td colSpan={2} style={{ padding: 10, textAlign: 'right' }}>TOTAL:</td>
                       <td style={{ padding: 10, textAlign: 'right' }}>{fmtNumber(data.financial_summary.gross_revenue)}</td>
                       <td style={{ padding: 10, textAlign: 'right' }}>{fmtNumber(data.financial_summary.gross_revenue)}</td>
                    </tr>
                 </tfoot>
              </table>
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10 }}>
                 <button className="btn btn-outline" onClick={() => setSapModalOpen(false)}>Cancel</button>
                 <button
                   className="btn btn-primary"
                   style={{ background: '#8e44ad' }}
                   onClick={() => alert(
                     'Not exported.\n\n'
                     + 'The SAP BAPI export is not built, and the amounts in this preview come from '
                     + 'the report stub rather than settled trades.'
                   )}
                 >Download CSV for SAP BAPI</button>
              </div>
           </div>
        </div>
      )}

      {/* PDF View Modal */}
      {pdfModalOpen && data?.financial_summary && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.7)', zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
           <div style={{ background: '#fff', width: '90%', height: '90%', borderRadius: 8, display: 'flex', flexDirection: 'column', overflow: 'hidden', boxShadow: '0 4px 20px rgba(0,0,0,0.3)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: 15, background: '#f8f9fa', borderBottom: '1px solid #dee2e6' }}>
                 <h3 style={{ margin: 0 }}>Document Viewer - IEX261123DOR_PTC0850_HP0_Naitwar_Mori_HPS.pdf</h3>
                 <button onClick={() => setPdfModalOpen(false)} style={{ background: 'none', border: 'none', fontSize: 24, cursor: 'pointer', lineHeight: 1 }}>&times;</button>
              </div>
              <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
                 {/* Left Side: Mock PDF Frame */}
                 <div style={{ flex: 2, background: '#525659', display: 'flex', justifyContent: 'center', alignItems: 'center', padding: 20, overflowY: 'auto' }}>
                    <div style={{ background: '#fff', width: '100%', maxWidth: 800, minHeight: 1000, boxShadow: '0 0 10px rgba(0,0,0,0.5)', padding: 40 }}>
                       <h2 style={{ textAlign: 'center', textDecoration: 'underline' }}>DAILY OBLIGATION SUMMARY REPORT (REPORT - I)</h2>
                       <table style={{ width: '100%', marginTop: 30, borderCollapse: 'collapse', fontSize: 14 }}>
                          <tbody>
                             <tr><td style={{ padding: 8, border: '1px solid #000' }}>Trading Date</td><td style={{ padding: 8, border: '1px solid #000' }}>26-Nov-23</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000' }}>Delivery Date</td><td style={{ padding: 8, border: '1px solid #000' }}>27-Nov-23</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000' }}>Entity Name</td><td style={{ padding: 8, border: '1px solid #000' }}>PTC India Ltd.</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000' }}>Portfolio Name</td><td style={{ padding: 8, border: '1px solid #000' }}>Naitwar_Mori_HPS</td></tr>
                          </tbody>
                       </table>
                       <table style={{ width: '100%', marginTop: 30, borderCollapse: 'collapse', fontSize: 14 }}>
                          <thead>
                             <tr>
                                <th scope="col" style={{ padding: 8, border: '1px solid #000', textAlign: 'left' }}>LINE ITEM DESCRIPTION</th>
                                <th scope="col" style={{ padding: 8, border: '1px solid #000', textAlign: 'right' }}>AMOUNT IN ₹</th>
                             </tr>
                          </thead>
                          <tbody>
                             <tr><td style={{ padding: 8, border: '1px solid #000' }}>Funds Payin(-) / Payout(+)</td><td style={{ padding: 8, border: '1px solid #000', textAlign: 'right' }}>13,21,932.90</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000', paddingLeft: 20 }}>- NLDC Application Fees</td><td style={{ padding: 8, border: '1px solid #000', textAlign: 'right' }}>-7.56</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000', paddingLeft: 20 }}>- STU Transmission Charges</td><td style={{ padding: 8, border: '1px solid #000', textAlign: 'right' }}>-24,289.07</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000', paddingLeft: 20 }}>- SLDC Scheduling and Operating Charges</td><td style={{ padding: 8, border: '1px solid #000', textAlign: 'right' }}>-2,000.00</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000' }}>Fees</td><td style={{ padding: 8, border: '1px solid #000', textAlign: 'right' }}>-7,175.50</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000' }}>GST Breakup (IGST)</td><td style={{ padding: 8, border: '1px solid #000', textAlign: 'right' }}>-1,291.59</td></tr>
                             <tr><td style={{ padding: 8, border: '1px solid #000', fontWeight: 'bold' }}>TOTAL NET PAYOUT</td><td style={{ padding: 8, border: '1px solid #000', textAlign: 'right', fontWeight: 'bold' }}>12,87,169.18</td></tr>
                          </tbody>
                       </table>
                    </div>
                 </div>
                 {/* Right Side: DB Parsed Verification */}
                 <div style={{ flex: 1, background: '#fff', borderLeft: '1px solid #ccc', padding: 20, overflowY: 'auto' }}>
                    <h3>Verification Status</h3>
                    <div style={{ marginBottom: 20 }}>
                       <Badge type="success">PDF Hash Verified</Badge>
                       <Badge type="success" style={{ marginLeft: 10 }}>Synced with SAP</Badge>
                    </div>
                    <div style={{ background: '#f5f7f9', padding: 15, borderRadius: 4, border: '1px solid #ddd' }}>
                       <h4 style={{ margin: '0 0 10px 0', color: '#2c3e50' }}>Parsed Database Metrics</h4>
                       <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                          <span style={{ color: '#555' }}>Gross Revenue:</span>
                          <strong>₹ {fmtNumber(data.financial_summary.gross_revenue)}</strong>
                       </div>
                       <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                          <span style={{ color: '#555' }}>Total Deductions:</span>
                          <strong style={{ color: '#c0392b' }}>- ₹ {fmtNumber(data.financial_summary.nldc_fee + data.financial_summary.stu_charges + data.financial_summary.sldc_charges + data.financial_summary.iex_fees + data.financial_summary.igst)}</strong>
                       </div>
                       <div style={{ borderBottom: '1px solid #ccc', margin: '10px 0' }}></div>
                       <div style={{ display: 'flex', justifyContent: 'space-between', color: '#27ae60', fontSize: 16 }}>
                          <span>Net System Payout:</span>
                          <strong>₹ {fmtNumber(data.financial_summary.net_payout)}</strong>
                       </div>
                    </div>
                    <p style={{ fontSize: 12, color: '#7f8c8d', marginTop: 20 }}>
                       The system automatically parses Page 1 (Report - I) of the Official IEX PDF to extract the financial settlement metrics and validates them against internal trading calculations.
                    </p>
                 </div>
              </div>
           </div>
        </div>
      )}
    </div>
  );
}
