/**
 * Column configs for IEX Bid Book Request reports (ISET layout).
 */

export const DAM_SINGLE_COLUMNS = [
  { key: 'sl_no', label: 'Sl No.' },
  { key: 'order_id', label: 'Order ID' },
  { key: 'order_time', label: 'Order Time' },
  { key: 'order_entry_time', label: 'Order Entry Time' },
  { key: 'delivery_date', label: 'Delivery Date' },
  { key: 'asset_id', label: 'Asset ID' },
  { key: 'bid_area_id', label: 'Bid Area ID' },
  { key: 'user_id', label: 'User ID' },
  { key: 'participant_id', label: 'Participant ID' },
  { key: 'portfolio_id', label: 'Portfolio ID' },
  { key: 'from_period_id', label: 'From Period ID' },
  { key: 'to_period_id', label: 'To Period ID' },
  { key: 'buy_sell', label: 'Buy/Sell (B/S)' },
  { key: 'transaction_serial_no', label: 'Transaction Serial No' },
  { key: 'extreme_price_range', label: 'Extreme Price Range' },
  { key: 'price_cutoff_missing', label: 'Price CutOff Missing' },
  { key: 'initiated_by', label: 'Initiated By' },
  { key: 'order_entered_by', label: 'Order Entered By' },
  { key: 'last_updated_time', label: 'Last Updated Time' },
  { key: 'total_executed_qty', label: 'Total Executed Qty' },
  { key: 'trade_price', label: 'Trade Price' },
  { key: 'ocf_opted', label: 'OCF Opted' },
  { key: 'premium_discount_price', label: 'Premium/Discount Price' },
  { key: 'max_ocf_quantity', label: 'Max OCF Quantity' },
  { key: 'ocf_source_bid_category', label: 'OCF Source Bid Category' },
  { key: 'ocf_source_order_id', label: 'OCF Source Order ID' },
  { key: 'error', label: 'Error' },
  { key: 'order_status', label: 'Order Status' },
  { key: 'action', label: 'Action' },
];

export const DAM_BLOCK_COLUMNS = [
  { key: 'sl_no', label: 'Sl No.' },
  { key: 'order_id', label: 'Order ID' },
  { key: 'delivery_date', label: 'Delivery Date' },
  { key: 'asset_id', label: 'Asset ID' },
  { key: 'bid_area_id', label: 'Bid Area ID' },
  { key: 'user_id', label: 'User ID' },
  { key: 'participant_id', label: 'Participant ID' },
  { key: 'portfolio_id', label: 'Portfolio ID' },
  { key: 'link_order_id', label: 'Link Order ID' },
  { key: 'order_time', label: 'Order Time' },
  { key: 'order_entry_time', label: 'Order Entry Time' },
  { key: 'order_type', label: 'Order Type' },
  { key: 'from_period_id', label: 'From Period ID' },
  { key: 'to_period_id', label: 'To Period ID' },
  { key: 'transaction_serial_no', label: 'Transaction Serial No' },
  { key: 'price', label: 'Price' },
  { key: 'quantity', label: 'Quantity' },
  { key: 'min_quantity', label: 'Min Quantity' },
  { key: 'no_sub_bids', label: 'No Sub Bids' },
  { key: 'total_executed_qty', label: 'Total Executed Qty' },
  { key: 'avg_trade_price', label: 'Avg Trade Price' },
  { key: 'bid_ref', label: 'Bid Ref' },
  { key: 'linked_bid_ref', label: 'Linked Bid Ref' },
  { key: 'buy_sell', label: 'Buy/Sell (B/S)' },
  { key: 'link_type', label: 'Link Type' },
  { key: 'error', label: 'Error' },
  { key: 'initiated_by', label: 'Initiated By' },
  { key: 'order_entered_by', label: 'Order Entered By' },
  { key: 'last_updated_time', label: 'Last Updated Time' },
  { key: 'ocf_opted', label: 'OCF Opted' },
  { key: 'premium_discount_price', label: 'Premium/Discount Price' },
  { key: 'max_ocf_quantity', label: 'Max OCF Quantity' },
  { key: 'ocf_source_bid_category', label: 'OCF Source Bid Category' },
  { key: 'ocf_source_order_id', label: 'OCF Source Order ID' },
  { key: 'order_status', label: 'Order Status' },
  { key: 'action', label: 'Action' },
];

export const RTM_SINGLE_COLUMNS = [
  { key: 'sl_no', label: 'Sl No.' },
  { key: 'delivery_date', label: 'Delivery Date' },
  { key: 'asset_id', label: 'Asset ID' },
  { key: 'bid_area_id', label: 'Bid Area ID' },
  { key: 'user_id', label: 'User ID' },
  { key: 'participant_id', label: 'Participant ID' },
  { key: 'portfolio_id', label: 'Portfolio ID' },
  { key: 'order_id', label: 'Order ID' },
  { key: 'order_time', label: 'Order Time' },
  { key: 'order_entry_time', label: 'Order Entry Time' },
  { key: 'session', label: 'Session' },
  { key: 'from_period_id', label: 'From Period ID' },
  { key: 'to_period_id', label: 'To Period ID' },
  { key: 'buy_sell', label: 'Buy/Sell (B/S)' },
  { key: 'transaction_serial_no', label: 'Transaction Serial No' },
  { key: 'error', label: 'Error' },
  { key: 'initiated_by', label: 'Initiated By' },
  { key: 'order_entered_by', label: 'Order Entered By' },
  { key: 'last_updated_time', label: 'Last Updated Time' },
  { key: 'total_executed_qty', label: 'Total Executed Qty' },
  { key: 'trade_price', label: 'Trade Price' },
  { key: 'order_status', label: 'Order Status' },
  { key: 'action', label: 'Action' },
];

export const RTM_BLOCK_COLUMNS = [
  { key: 'sl_no', label: 'Sl No.' },
  { key: 'delivery_date', label: 'Delivery Date' },
  { key: 'asset_id', label: 'Asset ID' },
  { key: 'bid_area_id', label: 'Bid Area ID' },
  { key: 'user_id', label: 'User ID' },
  { key: 'participant_id', label: 'Participant ID' },
  { key: 'portfolio_id', label: 'Portfolio ID' },
  { key: 'order_id', label: 'Order ID' },
  { key: 'link_order_id', label: 'Link Order ID' },
  { key: 'order_time', label: 'Order Time' },
  { key: 'order_entry_time', label: 'Order Entry Time' },
  { key: 'session', label: 'Session' },
  { key: 'from_period_id', label: 'From Period ID' },
  { key: 'to_period_id', label: 'To Period ID' },
  { key: 'buy_sell', label: 'Buy/Sell (B/S)' },
  { key: 'transaction_serial_no', label: 'Transaction Serial No' },
  { key: 'price', label: 'Price' },
  { key: 'quantity', label: 'Quantity' },
  { key: 'total_executed_qty', label: 'Total Executed Qty' },
  { key: 'avg_trade_price', label: 'Avg Trade Price' },
  { key: 'bid_ref', label: 'Bid Ref' },
  { key: 'linked_bid_ref', label: 'Linked Bid Ref' },
  { key: 'link_type', label: 'Link Type' },
  { key: 'error', label: 'Error' },
  { key: 'initiated_by', label: 'Initiated By' },
  { key: 'order_entered_by', label: 'Order Entered By' },
  { key: 'last_updated_time', label: 'Last Updated Time' },
  { key: 'order_status', label: 'Order Status' },
  { key: 'action', label: 'Action' },
];

export const BID_BOOK_REPORTS = {
  'dam-single': {
    title: 'DAM Single Bid Book Request Report',
    reportType: 'DAM_SINGLE',
    columns: DAM_SINGLE_COLUMNS,
  },
  'dam-block': {
    title: 'DAM Block Bid Book Request Report',
    reportType: 'DAM_BLOCK',
    columns: DAM_BLOCK_COLUMNS,
  },
  'rtm-single': {
    title: 'RTM Single Bid Book Request Report',
    reportType: 'RTM_SINGLE',
    columns: RTM_SINGLE_COLUMNS,
  },
  'rtm-block': {
    title: 'RTM Block Bid Book Request Report',
    reportType: 'RTM_BLOCK',
    columns: RTM_BLOCK_COLUMNS,
  },
};
