import { Router } from 'express';
import db from '../db/index.js';
import { requireAuth, requireRole, ROLE_GROUPS } from '../middleware/auth.js';
import { newId, genApplicationNo } from '../util.js';
import { secureLogAudit } from '../auditEngine.js';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

// Real applicant and seller names off the live portal, so the sample rows sit in
// the ignored src/data/live/ instead of inline here.
const SEED_PATH = join(dirname(fileURLToPath(import.meta.url)), '../data/live/bilateralApplicationSeeds.json');
function liveSeeds() {
  try {
    const rows = JSON.parse(readFileSync(SEED_PATH, 'utf8'));
    return Array.isArray(rows) ? rows : [];
  } catch {
    return [];
  }
}

const router = Router();
router.use(requireAuth);

/** Seed ISET-style Bilateral Applications once (NDMC buyer desk). */
export function seedBilateralApplications() {
  const n = db.prepare('SELECT COUNT(*) AS n FROM bilateral_applications').get().n;
  if (n > 0) return;

  const samples = liveSeeds();
  if (!samples.length) return;

  const insert = db.prepare(`
    INSERT INTO bilateral_applications (
      id, application_id, application_date, applicant, seller_name, buyer_name, status
    ) VALUES (?, ?, ?, ?, ?, ?, 'SUBMITTED')
  `);
  const tx = db.transaction(() => {
    for (const s of samples) {
      insert.run(newId('BAP'), s.application_id, s.application_date, s.applicant || 'SJVN Limited', s.seller_name, s.buyer_name);
    }
  });
  tx();
}

function findApp(idOrAppId) {
  return db.prepare('SELECT * FROM bilateral_applications WHERE id = ? OR application_id = ?')
    .get(idOrAppId, idOrAppId);
}

function formatCsvLines(row, party) {
  const lines = [
    ['Field', 'Value'].join(','),
    ['Application Id', row.application_id],
    ['Application Date', row.application_date],
    ['Applicant', row.applicant],
    ['Seller Name', row.seller_name],
    ['Buyer Name', row.buyer_name],
    ['Seller Contract', row.seller_contract_no || ''],
    ['Buyer Contract', row.buyer_contract_no || ''],
    ['Format Party', party],
    ['Status', row.status],
  ].map(([k, v]) => `"${k}","${String(v ?? '').replace(/"/g, '""')}"`);
  return lines.join('\n');
}

function formatText(row, formatLabel, party) {
  return [
    `${formatLabel} — Bilateral Application`,
    `Application Id: ${row.application_id}`,
    `Date: ${row.application_date}`,
    `Applicant: ${row.applicant}`,
    `Seller: ${row.seller_name}`,
    `Buyer: ${row.buyer_name}`,
    party ? `Party copy: ${party}` : '',
    `Status: ${row.status}`,
    '',
    'Generated by SJVN REIA & Power Trading Portal',
  ].filter(Boolean).join('\n');
}

router.get('/', requireRole(...ROLE_GROUPS.TRADING_ALL), (req, res) => {
  const { q } = req.query;
  let sql = 'SELECT * FROM bilateral_applications WHERE 1=1';
  const params = [];
  if (q) {
    sql += ` AND (
      application_id LIKE ? OR applicant LIKE ? OR seller_name LIKE ? OR buyer_name LIKE ?
    )`;
    const like = `%${q}%`;
    params.push(like, like, like, like);
  }
  sql += ' ORDER BY application_date DESC';
  res.json(db.prepare(sql).all(...params));
});

/** Format-I (common / application summary). */
router.get('/:id/format-i', requireRole(...ROLE_GROUPS.TRADING_ALL), (req, res) => {
  const row = findApp(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  const body = formatText(row, 'Format-I', null);
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${row.application_id}-Format-I.txt"`);
  res.send(body);
});

/** Format-II (buyer or seller copy). */
router.get('/:id/format-ii', requireRole(...ROLE_GROUPS.TRADING_ALL), (req, res) => {
  const row = findApp(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  const party = String(req.query.party || 'Buyer').toLowerCase() === 'seller' ? 'Seller' : 'Buyer';
  const body = formatText(row, 'Format-II', party);
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${row.application_id}-Format-II-${party}.txt"`);
  res.send(body);
});

/** Per-application request CSV. */
router.get('/:id/csv', requireRole(...ROLE_GROUPS.TRADING_ALL), (req, res) => {
  const row = findApp(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  const party = req.query.party || 'All';
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${row.application_id}.csv"`);
  res.send(formatCsvLines(row, party));
});

router.get('/:id', requireRole(...ROLE_GROUPS.TRADING_ALL), (req, res) => {
  const row = findApp(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  res.json(row);
});

/**
 * Create from bidding (or manual). If application_id omitted, mint via genApplicationNo.
 */
router.post('/', requireRole(...ROLE_GROUPS.TRADING_WRITE), (req, res) => {
  const b = req.body || {};
  const errors = [];
  if (!String(b.seller_name || '').trim()) errors.push('seller_name is required');
  if (!String(b.buyer_name || '').trim()) errors.push('buyer_name is required');
  if (errors.length) return res.status(400).json({ error: errors[0], errors });

  const applicationDate = b.application_date || new Date().toISOString().slice(0, 19).replace('T', ' ');
  const region = String(b.region || 'NR').toUpperCase();
  let applicationId = String(b.application_id || '').trim();
  if (!applicationId) {
    applicationId = genApplicationNo(applicationDate.slice(0, 10), region);
  }
  if (db.prepare('SELECT 1 FROM bilateral_applications WHERE application_id = ?').get(applicationId)) {
    return res.status(400).json({ error: `application_id ${applicationId} already exists` });
  }

  const id = newId('BAP');
  db.prepare(`
    INSERT INTO bilateral_applications (
      id, application_id, application_date, applicant, seller_name, buyer_name,
      bidding_id, seller_contract_no, buyer_contract_no, status, created_by
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'SUBMITTED', ?)
  `).run(
    id,
    applicationId,
    applicationDate,
    String(b.applicant || 'SJVN Limited').trim(),
    String(b.seller_name).trim(),
    String(b.buyer_name).trim(),
    b.bidding_id || null,
    b.seller_contract_no || null,
    b.buyer_contract_no || null,
    req.user?.id || null,
  );

  secureLogAudit(req, {
    action: 'CREATE_BILATERAL_APPLICATION',
    module: 'TRADING',
    entityType: 'bilateral_application',
    entityId: id,
    details: { application_id: applicationId, seller_name: b.seller_name, buyer_name: b.buyer_name },
  });

  res.status(201).json(db.prepare('SELECT * FROM bilateral_applications WHERE id = ?').get(id));
});

export default router;
