export const ROLE_GROUPS = {
  REIA_ALL: ['SJVN_ADMIN', 'REIA_USER', 'FINANCE_USER', 'MANAGEMENT'],
  REIA_WRITE: ['SJVN_ADMIN', 'REIA_USER'],
  TRADING_ALL: ['SJVN_ADMIN', 'TRADING_USER', 'FINANCE_USER', 'MANAGEMENT'],
  TRADING_WRITE: ['SJVN_ADMIN', 'TRADING_USER'],
};
